image_selected:
  type: aimg
  value: textures/InterfaceButton.png
image_highlighted:
  type: aimg
  value: textures/InterfaceButtonH.png

font_size: 22
font_bold: true
font: arial

color_red: 240
color_green: 240
color_blue: 240

padding: 15
