image_selected:
  type: aimg
  value: textures/MenuPauseButton.png
image_highlighted:
  type: aimg
  value: textures/MenuPauseButtonH.png

font_size: 20
font_bold: true
font: arial

color_red: 240
color_green: 240
color_blue: 240
